/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.google.common.base.Charsets;
import com.google.common.io.Files;
import com.jwcrain.autocomplete.App;
import com.jwcrain.autocomplete.PrefixTrie;
import org.junit.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAutocomplete() throws Exception {
        String path = getClass().getClassLoader().getResource("words_alpha.txt").getFile();
        System.out.printf("Loading word list into memory\n");
        List<String> words = Files.readLines(new File(path), Charsets.UTF_8);
        System.out.printf("Building prefix tree with %d words\n", words.size());
        PrefixTrie prefixTrie = new PrefixTrie();
        for (int i = 0; i < words.size(); i++) {
            prefixTrie.insertWord(words.get(i).trim());
        }
        prefixTrie.search("aard");
    }
}
